module.exports={
    DmSans_Regular:"DMSansRegular",
    DmSans_Bold:"DMSansBold",
    DmSans_Medium:"DMSansMedium",
    OpenSans_SemiBold:"OpenSansSemiBold",
    OpenSans_Bold:"OpenSansBold",
    OpenSans_Regular:"OpenSansRegular",
    OpenSans_ExtraBold:"OpenSansExtraBold"   
}